### ISSUE TITLE
KeyError: 'tabs_stack'

### ISSUE THREAD

**Issue by barbaricyawps** [executablebooks/sphinx-tabs#161]
### Describe the bug

**context**
Hi, Sphinx Tabs friends! I'm trying to convert my docs to use sphinx-tabs instead of sphinx-inline-tabs because I think your tabs are rendered in a slightly more user-friendly way.

FYI, I'm building Sphinx using nox and venv environments and that might possibly be a factor.

When I try to build my Sphinx docs with your extension (running version 3.3.1), I get a build error with a KeyError exit code (see error message below).

**expectation**
The Sphinx docs build should succeed, not fail. I seem to be able to do this exact same process on a different doc set using the same tools, so I don't know why I only get this bug in this environment.

**bug**
I get this error message when the Sphinx build fails:

```
Exception occurred:
  File "/my-directory/lib/python3.10/site-packages/sphinx_tabs/tabs.py", line 143, in run
    tabs_id = self.env.temp_data["tabs_stack"][-1]
KeyError: 'tabs_stack'
The full traceback has been saved in /tmp/sphinx-err-m8zbbkt6.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**problem**
This is a problem for people building Sphinx docs because the build fails. Basically this one error prevents me from building my entire doc set. I'm also not super great at parsing and reading Python yet, so I don't know how to troubleshoot it myself. I'll get there.

Is it maybe some sort of packaging dependency that is having an error or is it a code problem?

### Reproduce the bug

I can provide the error log if you need!

### List your environment

I use the latest Sphinx that builds my docs using nox inside of a virtual environment (venv).

**Comment by foster999** [comment]
Hi @barbaricyawps, please could you provide a link to your project docs or a minimal example in markdown/rst that causes the same error?

**Comment by foster999** [comment]
Please also review the example usage in our documentation, as it differs from sphinx-in line-tabs. It's possible that you're not wrapping 'tab' directives in a '' tabs' directive.

**Comment by barbaricyawps** [comment]
Thanks so much for your reply! Here's the project that I'm hoping to switch from inline tabs to sphinx-tabs: https://gitlab.com/saltstack/open/docs/salt-install-guide

I'll double-check. We use sphinx-tabs on another project: https://gitlab.com/saltstack/open/docs/salt-user-guide

Because of that repo, I definitely know I can get it to work with the correct syntax. I'll double-check, though!

**Comment by foster999** [comment]
Sorry, both of those links are to the second project that uses sphinx-tabs.

If the syntax does appear to be correct, please can you point me to an example using sphinx-tabs that is failing to build?

**Comment by foster999** [comment]
No worries 😊

Thanks for sharing the additional links! I'm afraid I can't really help without seeing an example of the sphinx-tabs rst that reproduces the error (don't worry about the rendered version). You could share:
1. A link to your working branch, if you push it up to the remote on GitLab
2. A GitHub Gist containing an example of the sphinx-tabs rst that is failing to build
3. A pasted code block here, showing sphinx-tabs rst that is failing to build

Note that for 2 or 3 you'll need to ensure that specific example doesn't build on it's own (i.e. When building only that page, with all other pages deleted). In doing this, you'll probably find the troublesome rst anyways 😁

I don't think this is causing your issue, but just to note that the sphinx-tabs guidance in the last set of links above could be made more concise using the 'code-tab' directive instead of nesting 'code-block' inside of a standard 'tab'.

**Comment by foster999** [comment]
I'm assuming that the syntax error was found here, so closing the issue for now. Please feel free to comment again if the issue remains and you'd like further help
