### ISSUE TITLE
RFE: please provide support for `jinja2` >= 3.0.0

### ISSUE THREAD

**Issue by kloczek** [executablebooks/sphinx-tabs#166]
https://github.com/executablebooks/sphinx-tabs/blob/b9fd7d81147c20da11960cb0f296ec9a55845c06/setup.py#L28

**Comment by kloczek** [comment]
Actually just found that this install time dependency cen be dropped
```console
[tkloczko@devel-g2v sphinx-tabs-3.4.0]$ grep -r jinja2
setup.py:    install_requires=["sphinx>=2,<6", "pygments", "docutils~=0.17.0", "jinja2<3.1.0"],
```

**Comment by foster999** [comment]
This was added in #164 because later versions of jinja2 seem to be incompatible with sphinx. Running the tests without that dependency specified shows that sphinx imports a depreciated jinja2 object.

We could make the requirement more specific if we can identify when the breaking change was included? Otherwise, this might be an issue for sphinx to support the latest versions of jinja2?

**Comment by foster999** [comment]
So it looks like this [has already been addressed in the latest versions of sphinx](https://github.com/sphinx-doc/sphinx/issues/10291). I think our solution would be to follow sphinx and only officially support their latest version, because it would be too much faff to manage the dependencies for older sphinx versions

**Comment by kloczek** [comment]
```console
[tkloczko@devel-g2v g2v]$ pip show sphinx
Name: Sphinx
Version: 5.0.2
Summary: Python documentation generator
Home-page: https://www.sphinx-doc.org/
Author: Georg Brandl
Author-email: georg@python.org
License: BSD
Location: /usr/lib/python3.8/site-packages
Requires: alabaster, babel, docutils, imagesize, importlib-metadata, Jinja2, packaging, Pygments, requests, snowballstemmer, sphinxcontrib-applehelp, sphinxcontrib-devhelp, sphinxcontrib-htmlhelp, sphinxcontrib-jsmath, sphinxcontrib-qthelp, sphinxcontrib-serializinghtml
Required-by:
```
As you see `sphinx` has now `jinnja2` on list of its dependencies.

**Comment by foster999** [comment]
The issue here was due to `jinja2` not being listed in their dependencies in older `sphinx` versions that we were trying to support. But I think this has highlighted that we don't need to try to support older versions, so thanks :)

**Comment by kloczek** [comment]
IIRC it is possible to make conditional dependencies.
In case of sphins 5.x clearly that dependency is redundant.

**Comment by foster999** [comment]
Jinja version no longer pinned from v3.4.1 👍🏻

**Comment by kloczek** [comment]
Thank you.
Just added that PR to my build procedure and so far all look good 👍
