### ISSUE TITLE
Support for `include` directive in tabs

### ISSUE THREAD

**Issue by JSS95** [executablebooks/sphinx-tabs#172]
### Context

Sphinx's `include` directive allows including the entire code from another file.

```
.. include:: my/code.py
   :code: python
```

It would be nice if we had this feature in code tabs.

### Proposal

# Propsal A: allow `include` nested in `code-tab`

```
.. tabs::

   .. code-tab::

      .. include:: my/code.py
         :code: python
```

# Proposal B: add `:include:` option to `code-tab`

```
.. tabs::

   .. code-tab::
      :include: my/code.py
```

**Comment by foster999** [comment]
Thanks for getting in touch!

Please could you try using 'include' within a normal 'tab' directive, instead of a 'code-tab'?

The 'code-tab' puts all of the content within a code block, which can't be nested in. I believe that 'include' creates its own code block, so using it in a normal tab should give the desired result. Please let me know if this doesn't work 😄

**Comment by JSS95** [comment]
Thank you, @foster999. That worked!
I think it would be good to have this documented so I opened #173.
