### ISSUE TITLE
Unpleasant line under the tab names

### ISSUE THREAD

**Issue by filippo82** [executablebooks/sphinx-tabs#65]
Dear all,

I am using sphinx-tabs inside a [Jupyter Book](https://jupyterbook.org/) and I see this:
<img width="616" alt="Screenshot 2020-05-11 at 20 06 17" src="https://user-images.githubusercontent.com/5595364/81595962-92dbb700-93c3-11ea-99f7-63cec37f39d1.png">
where you can see a line dividing the tab and the content below it. Such line is not present in the examples shown [here](https://github.com/djungelorm/sphinx-tabs).

Any clues?

I could try to provide you with additional information.

Thank you.
-Filippo

**Comment by stefanodavid** [comment]
Hi @filippo82, I suspected this could be due to some interaction between sphinx-tabs and other extensions. 

I followed the link to the repo you linked and discovered two new useful extensions (hey, many thanks for that!), so I tried them out and I ended up with almost the same case. If I remove the custom CSS of this extension from the build directory, the "unpleasant line" is gone.

**Comment by filippo82** [comment]
Hi @stefanodavid,

thanks for the reply.

Could you tell me the location of that custom CSS extension within the build directory?

Ciao.

**Comment by stefanodavid** [comment]
Hi @filippo82, 

sphinx_tabs CSS is under _static/sphinx_tabs/tabs.css with a few more under _static/sphinx_tabs/semantic-ui-2.4.1/

The other extensions to which I am referring place their CSS files directly under _static/.

Hope this helps,
Stefano

**Comment by foster999** [comment]
I've used the following custom CSS to override the properties causing the misalignment of tabs and leaving the bottom border visible. This works for a  `jupyter-book`:

```
.sphinx-tabs .sphinx-menu {
    padding-left: 0;
    padding-right: 0;
}

main.bd-content #main-content div.sphinx-tabs > div.menu > a.active.item {
    margin-bottom: -1px;
}
```
