### ISSUE TITLE
Compatibility with pydata_sphinx_theme

### ISSUE THREAD

**Issue by MalteKurz** [executablebooks/sphinx-tabs#90]
* I would like to use `sphinx-tabs` in a project with `pydata_sphinx_theme` (https://github.com/pandas-dev/pydata-sphinx-theme). Unfortunately, they don't seem to be compatible.
* Using the example code together with the option `html_theme = 'pydata_sphinx_theme'` in the conf.py results in the following behavior.
![image](https://user-images.githubusercontent.com/7427117/92763943-46fe4600-f394-11ea-881d-613416696341.png)
* Do you have any idea how to achieve compatibility? Any help would be very much appreciated.

Versions used: python 3.8.2, pydata_sphinx_theme 0.3.2, sphinx-tabs 1.3.0, sphinx 3.2.1

**Comment by chrisjsewell** [comment]
Heya, is this the same in earlier versions, e.g. 1.2?
Maybe something recently broke it because last time I checked it was working with sphinx-book-theme. 
Anyway, we should employ here my nice multi-theme set up in https://sphinx-panels.readthedocs.io/en/pydata-theme/

**Comment by chrisjsewell** [comment]
Also there is now a pydata-sphinx-theme v0.4

**Comment by MalteKurz** [comment]
Thanks for the quick reply. The multi-theme setup looks very nice.

I locally checked the following combinations:
* With sphinx_tabs 1.3.0 the themes alabaster 0.7.12, sphinx-rtd-theme 0.5.0 & sphinx-book-theme 0.0.36 are fine, but sphinx-pydata-theme 0.4.0 not.
* With sphinx_tabs 1.2.0 I get the same results (theme versions as mentioned above).

**Comment by chrisjsewell** [comment]
It may be because sphinx tabs uses `nodes.container` for all of these elements. These are converted in the HTML to

```html
<div class="container"></div>
```

The Bootstrap CSS framework that `pydata-sphinx-theme` uses has a special meaning for the `container` class though, which may be clashing with the CSS from this package.
sphinx-book-theme also uses Bootstrap though, so I'm surprised that works.

Anyway, in sphinx-panels I use a "special" `div` sub-class of `nodes.container`, which ensures that the "container" class name is not added to the output div.
It wouldn't hurt to add that here.
